
services:
  mongodb:
    image: mongo:6
    container_name: fastapi_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  api:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data: